Neos:
  Neos:
    userInterface:
      translation:
        autoInclude:
          Carbon.Navigation:
            - 'NodeTypes/*'
    fusion:
      autoInclude:
        Carbon.Navigation: true

Carbon:
  Navigation:
    redirect:
      statusCode: 301
