Neos:
  Neos:
    userInterface:
      translation:
        autoInclude:
          Carbon.Navigation:
            - 'NodeTypes/*'
    fusion:
      autoInclude:
        Carbon.Navigation: true

Carbon:
  Navigation:
    templatePath: 'resource://Carbon.Navigation/Private/Templates/Menu.html'
    useBEM: false
    Dimensions:
      namespace: dimensions
      renderCurrent: true
      wrapAnchor: false
      listTag: ul
      elementTag: li
    Menu:
      namespace: nav
      wrapText: false
      listTag: ul
      elementTag: li
      maximumLevels: 2
      filter: 'Neos.Neos:Document,!Carbon.Navigation:NotInMenu'
      showHome: false
    References:
      namespace: references
      wrapText: false
      listTag: ul
      elementTag: li
    redirect:
      statusCode: 301
